package io.clubone.transaction.exception;

public enum MethodArgumentExceptionMessage {
	ACCESS_NAME_IS_MISSING,
	ACCESS_NAME_IS_NOT_VALID,
	ACCESS_DESCRIPTION_IS_MISSING,
	FIRST_NAME_IS_MISSING,
	LAST_NAME_IS_MISSING,
	EMAIL_IS_MISSING,
	FIRST_NAME_IS_NOT_VALID,
	LAST_NAME_IS_NOT_VALID,
	EMAIL_IS_NOT_VALID,
	ROLE_NAME_IS_MISSING,
	ROLE_NAME_IS_NOT_VALID,
	ROLE_DESCRIPTION_IS_MISSING,
	ACCESS_DETAILS_MISSING;
}
