## PostgreSQL (same for test / stag / prod)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.clubone.jdbc-url=jdbc:postgresql://clubone-free-tier-db.cju8eqswasju.us-east-1.rds.amazonaws.com:5432/clubone_dev
spring.datasource.clubone.username=clubone_dev_user
spring.datasource.clubone.password=C1ub0ne@2024!
spring.datasource.clubone.driverClassName=org.postgresql.Driver
spring.datasource.clubone.hikari.maximum-pool-size=40
spring.datasource.clubone.hikari.minimum-idle=10
spring.datasource.clubone.hikari.connection-timeout=10000
spring.datasource.clubone.hikari.leak-detection-threshold=60000
spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.ddl-auto=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.generate_statistics=false
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

clubone.ms.service.host=https://clubone.io
payment.api.url=https://develop-api.clubone.io/payment/v1
client.agreement.service.base-url=https://develop-api.clubone.io/agreement/client-agreements/api/client-agreements
agreement.purchase.url=https://develop-api.clubone.io/agreement/membership/api/membership-sales
notification.payload.url=https://develop-api.clubone.io/transaction/notification/invoice/{invoiceId}/email-payload
notification.send.url=https://develop-api.clubone.io/notification/send

billing.quote.line-items.url=https://develop-api.clubone.io/vendors/billing/api/quote/line-items

clubone.integration.webhook.enabled=true
clubone.integration.webhook.publish-url=https://develop-api.clubone.io/integration/api/v1/webhook/events/publish
