## PostgreSQL
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.clubone.jdbc-url=jdbc:postgresql://clubone-postgres-instance.cju8eqswasju.us-east-1.rds.amazonaws.com:5432/clubone_dev
spring.datasource.clubone.username=dev_user
spring.datasource.clubone.password=dev_user
spring.datasource.clubone.driverClassName=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.ddl-auto=false
spring.jpa.properties.hibernate.default_schema=public


clubone.ms.service.host= https://clubone.io

clubone.integration.webhook.enabled=true
clubone.integration.webhook.publish-url=https://develop-api.clubone.io/integration/api/v1/webhook/events/publish
clubone.integration.webhook.default-application-id=5949a200-82fb-4171-9001-0f77ac439011
clubone.integration.webhook.system-actor-id=0bed5979-0a9c-4efc-af5b-d1a88cca73f8
